    <div>
      <a href="http://avsbq.org"><i>avsbq.org</i></a> |
      <a href="http://archive.avsbq.org">archive</a> -
      <a href="http://mal.avsbq.org">mal</a> -
      <a href="http://language.avsbq.org">languages</a> -
      <a href="http://link.avsbq.org">links</a> -
      <a href="http://iconography.avsbq.org">liturgical arts</a> -
      <a href="http://project.avsbq.org">projects</a> -
      <a href="http://tutorial.avsbq.org">tutorials</a> 
    </div>

    <div>
      <a href="http://profile.avsbq.org/"><i>profile</i></a> |
      <a href="http://avsbq.org/.videos">vids</a> -
      <a href="http://avsbq.org/.webring">webring</a>
    </div>

